import Head from 'next/head'
import Link from 'next/link'
import FirstTeamSection from '../components/FirstTeamSection'
import Footer from '../components/Footer'
import FunClub from '../components/FunClub'
import HeroSection from '../components/HeroSection'
import LatestResult from '../components/LatestResult'
import LatestVideo from '../components/LatestVideo'
import LeagueStatics from '../components/LeagueStatics'
import NavMenu from '../components/NavMenu'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <main >
        <NavMenu></NavMenu>
        <HeroSection></HeroSection>
        <LatestResult></LatestResult>
        <FirstTeamSection></FirstTeamSection>
        <LeagueStatics></LeagueStatics>
        {/* <LatestVideo></LatestVideo> */}
        <FunClub></FunClub>
      </main>

      <footer >
        <Footer></Footer>
      </footer>
    </div>
  )
}
